AllCops:
  Exclude:
    - 'config.ru'
    - 'db/**/*.rb'
    - 'db/schema.rb'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*.rb'

Layout/AlignHash:
  EnforcedColonStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Max: 80

Metrics/MethodLength:
  Max: 35

Metrics/ModuleLength:
  CountComments: false
  Max: 500
