default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ecampi_development
  host: ecampi_db
  username: postgres
  password: postgres

test:
  <<: *default
  database: ecampi_test
  host: ecampi_db
  username: postgres
  password: postgres

production:
  <<: *default
  database: ecampi_production
